
version: 2

models:
  - name: EthioMedDataWarehouse_dbt_model
    description: "EthioMedDataWarehouse dbt model"
    columns:
      - name: data_transformed
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
